name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Create `gh-pages` branch if it doesn't exist
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial commit"
            git push origin gh-pages
          fi

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          git add -A
          git commit -m "Deploy"
          git push origin gh-pages
